[project]
name = "streamlit-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "openai>=1.54.4",
    "pillow>=11.0.0",
    "python-dotenv>=1.0.1",
    "streamlit>=1.40.1",
    "watchdog>=6.0.0",
]
